version: '2.3'
services:
  apollo-federation-gateway:
    image: xmorse/apollo-federation-gateway
    ports:
      - 8000:80
    environment:
      CACHE_MAX_AGE: '5' # default cache
      ENGINE_API_KEY: '...' # to connect to the apollo engine
      POLL_INTERVAL: 30 # to update services changes
      URL_0: "http://host.docker.internal:8080/graphql"
      URL_1: "http://host.docker.internal:8081/graphql"
      URL_2: "http://host.docker.internal:8083/graphql"
      # you can also add other services outside docker
